config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'
  get 'auth/failure', to: redirect('/')
 
  resources :reviews

  resources :restaurants do
    resources :reviews, only: [:new, :index, :create]
  end 
  
  resources :categories
  resources :users

  get '/very_popular' => 'restaurants#very_popular'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password 
    has_many :reviews
    has_many :reviewed_restaurants, through: :reviews, source: :restaurant 

    has_many :restaurants   

    validates :username, :email, presence: true
    validates :username, :email, uniqueness: true 

    # def self.create_by_github_omniauth(auth)
    #     self.find_or_create_by(username: auth[:info][:email]) do |u|
    #       u.email = auth[:info][:email]  
    #       u.password = SecureRandom.hex
    
    #     end
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :redirect_if_not_logged_in, only: [:new, :create]
   
    def new 
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if  @user.valid?
            @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end 
    end 

    def show
        redirect_if_not_logged_in
        @user = User.find_by(id: params[:id])
        redirect_to '/' if !@user
    end 

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1> Sign Up Here! </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render 'layouts/errors' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Sign Up", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>    

app/views/users/show.html.erb
<h1>Hello, <%= @user.username %>! Welcome to your Restaurant Finder Home Page!</h1> 
<h2>Catalog all your favorite places to eat!</h2> 
<h3>Here are all <%= @user.username %>'s restaurants:</h3>
<ul>
  <% @user.restaurants.each do |r|%>
  <li> <%= link_to r.name_and_category, restaurant_path(r)%> </li>
  <% end %>
</ul>