config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'
  get 'auth/failure', to: redirect('/')
 
  resources :reviews

  resources :restaurants do
    resources :reviews, only: [:new, :index, :create]
  end 
  
  resources :categories
  resources :users

  get '/very_popular' => 'restaurants#very_popular'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :user
    belongs_to :category   
    has_many :reviews
    has_many :users, through: :reviews 

    #accepts_nested_attributes_for :company

    validates :name, presence: true  
    validates :address, uniqueness: true  
    validate :not_a_duplicate 

    scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')}
    scope :very_popular, -> {left_joins(:reviews).group(:id).order('count(reviews.id) desc').limit(3)}  

    def self.alpha
        order(:name) 
    end

    def category_attributes=(attributes)
        self.category = Category.find_or_create_by(attributes) if !attributes['name'].empty?
        self.category 
    end

    def not_a_duplicate
        # if there is already a restaurant with this name and address 
        restaurant = Restaurant.find_by(name: name, address: address) 
        if !!restaurant && restaurant != self
          errors.add(:name, 'has already been added for that address')
        end
    end 

    def category_name
        category.try(:name)
    end
    
    def name_and_category
        "#{name} - #{category.try(:name)}"
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_restaurant, only:[:show, :edit, :update]
    before_action :redirect_if_not_logged_in

    def new
        @restaurant = Restaurant.new 
        if params[:category_id]
            category = Category.find(params[:category_id])
            @restaurants = category.restaurants 
          
        else 
            @restaurants = Restaurant.order_by_rating.includes(:category) 
        end 
    end 

    def create
        @restaurant = Restaurant.new(restaurant_params)
        @restaurant.user_id = session[:user_id] 

        if @restaurant.save
            redirect_to restaurant_path(@restaurant)
        else 
            @restaurant.build_category
            render :new
        end 
    end 
    
    def index
        if params[:category_id]
            category = Category.find(params[:category_id])
            @restaurants = category.restaurants 
    
        else 
            @restaurants = Restaurant.order_by_rating.includes(:category) 
        end     
    end 

    def show
    end 

    def edit 
        if authorized_to_edit?(@restaurant) 
            render :edit   
           else 
            redirect_to restaurant_path(@restaurant)   
        end
    end 

    def update 
        @restaurant = Restaurant.find_by(id: params[:id])   
        if @restaurant.update(restaurant_params)
          redirect_to restaurant_path(@restaurant)
        else
          render :edit
        end 
    end

    def most_popular
    @restaurants = Restaurant.most_popular
    end 

    private

    def restaurant_params
        params.require(:restaurant).permit(:name, :price_range, :address, :category_id, category_attributes: [:name])
    end 

    def set_restaurant
        @restaurant = Restaurant.find_by(id: params[:id])
        redirect_to restaurants_path if !@restaurant 
    end

    def redirect_if_not_authorized 
        if @restaurant.update(name: params[:name], price_range: params[:price_range], address: params[:address])   
          redirect_to restaurant_path(@restaurant)
        else
          redirect_to user_path(current_user)     
        end 
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_errors.html.erb
<% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@restaurant.errors.count, "error") %>.
    </div>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f|%> 
    <%= render 'restaurants/errors' %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br><br>
    </div>
    
    <div>
      <%= f.label :price_range %> 
      <%= f.select :price_range,options_for_select(["$", "$$", "$$$"]), include_blank: true %>  
      <br><br>
    </div>
    <div>
      <%= f.label :address %>
      <%= f.text_field :address %> 
      <br><br>
    </div>

    <p> Select a Category that already exists: </p>
    <div>
      <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: 'Select One'%>
  
    </div>
  <br><br>
    <%= f.submit %>
  <% end %>

app/views/restaurants/edit.html.erb
<h1>Edit your Restaurant</h1>

<%= render partial: 'form'%>

app/views/restaurants/index.html.erb
<h1>All the Restaurants</h1> 
<%= form_tag('/restaurants',:method=>:get) do %>                          
<%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "name", params[:category_id]), include_blank: 'Select One' %>    
<%= submit_tag %>
<% end %>

<% @restaurants.each do |r| %>

 <h2><%= link_to r.name, restaurant_path(r.id)%> - <%= r.category.name %> - <%= r.price_range %> </h2>
  <%= link_to "Write a review", new_restaurant_review_path(r.id) %> 
  <br><br>
  <%= r.address %>
  <% end %>

app/views/restaurants/most_popular.html.erb
<% @restaurants.each do |r| %>
<%= r.name %> 
<% end %> 

app/views/restaurants/new.html.erb
<h1>Make a New Restaurant:</h1> 

<%= render 'form' %> 

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name%>  </h1>


<h2> <%= @restaurant.category_name %> </h2>
<div>
  <p><%= @restaurant.price_range %></p>
  <p><%= @restaurant.address %></p>
</div>


<%= link_to "Edit #{@restaurant.name}", edit_restaurant_path(@restaurant) if @restaurant.user == current_user%>

<br><br>

<%= link_to "See all Reviews", restaurant_reviews_path(@restaurant) %>

app/views/restaurants/very_popular.html.erb
<% @restaurants.each do |r| %>
<%= r.name %> 
<% end %> 