config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'
  get 'auth/failure', to: redirect('/')
 
  resources :reviews

  resources :restaurants do
    resources :reviews, only: [:new, :index, :create]
  end 
  
  resources :categories
  resources :users

  get '/very_popular' => 'restaurants#very_popular'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_loggedin_links.html.erb
<%= link_to "Log Out", logout_path, method: :delete %> |
<%= link_to "Add a Restaurant", new_restaurant_path %> |
<%= link_to "All Restaurants", restaurants_path %> |
<%= link_to "All Reviews", reviews_path %> |
<%= link_to "All Categories", categories_path %> |
<%= link_to "Home Screen", current_user %>

app/views/layouts/_loggedout_links.html.erb
<%= link_to "Login", login_path %> |
<%= link_to "Signup", signup_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  <br><br>
  
  <div><%= render_nav_bar %></div>
  
  <body>
    <%= yield %>
  </body>
</html>